
CREATE TABLE BOARD(
	RCD_NO INT AUTO_INCREMENT,
	GRP_NO INT,
	USR_NAME VARCHAR(30),
	USR_SUBJECT VARCHAR(30),
	USR_CONTENT VARCHAR(1000),
	USR_PASS VARCHAR(30),
	USR_FILENAME VARCHAR(30),
	USR_FILESIZE INT,
	USR_DATE VARCHAR(30),
	USR_REFER INT,
	RCD_LEVEL INT,
	RCD_ORDER INT,
	CONSTRAINT BOARD_PK PRIMARY KEY(RCD_NO)
);

INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'왕진지','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'초아','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'아이유','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'태연','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'유아인','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'이성한','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'홍길동','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'유지태','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'이나영','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'원빈','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'왕진지','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'왕진지','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'왕진지','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'왕진지','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'왕진지','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'왕진지','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'왕진지','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'왕진지','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);
INSERT INTO BOARD(GRP_NO, USR_NAME, USR_SUBJECT, USR_CONTENT, USR_PASS, USR_FILENAME, USR_FILESIZE,
				  USR_DATE, USR_REFER, RCD_LEVEL, RCD_ORDER)
VALUES(1,'왕진지','왕진지지함','안녕하세요요오무',NULL,NULL,NULL,now(),0,5,0);

